# Generated by Django 2.1.7 on 2019-03-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='state',
        ),
    ]
