# Generated by Django 2.1.7 on 2019-03-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0002_remove_employees_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
    ]
