# Generated by Django 2.1.7 on 2019-03-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0003_auto_20190315_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='move_tech',
            options={'verbose_name': 'Перемещение', 'verbose_name_plural': 'Перемещение'},
        ),
    ]
