# Generated by Django 2.1.7 on 2019-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0004_auto_20190315_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='fio',
            field=models.CharField(default='alex', max_length=150),
        ),
    ]
