# Generated by Django 2.1.7 on 2019-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0005_employees_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='fio',
            field=models.CharField(max_length=150),
        ),
    ]
