# Generated by Django 2.1.7 on 2019-04-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0007_auto_20190318_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='dept',
            field=models.CharField(default='АСУП', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Employees', verbose_name='Сотрудник'),
        ),
    ]
