# Generated by Django 2.1.7 on 2019-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0008_auto_20190402_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='room',
            field=models.CharField(default='444', max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.CharField(max_length=50, verbose_name='Отдел'),
        ),
    ]
