# Generated by Django 2.1.7 on 2019-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0010_auto_20190403_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
    ]
