# Generated by Django 2.1.7 on 2019-04-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0011_auto_20190403_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='mac_address',
        ),
    ]
