# Generated by Django 2.1.7 on 2019-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0013_auto_20190403_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='fio',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='room',
            field=models.CharField(max_length=50, verbose_name='Кабинет'),
        ),
    ]
