# Generated by Django 2.1.7 on 2019-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0014_auto_20190403_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='fio',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О.(Полностью)'),
        ),
    ]
