# Generated by Django 2.1.7 on 2019-04-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0015_auto_20190403_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_to_repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Employees', verbose_name='Заявитель')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, default='0-53999', max_length=100, verbose_name='ИНВ №'),
        ),
    ]
