# Generated by Django 2.1.7 on 2019-04-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0019_auto_20190403_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_to_repair',
            name='inventory_number',
        ),
        migrations.AddField(
            model_name='request_to_repair',
            name='number',
            field=models.ForeignKey(db_column='number_inventory_number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Equipment', verbose_name='ИНВ №'),
        ),
    ]
