# Generated by Django 2.1.7 on 2019-04-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0020_auto_20190403_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_to_repair',
            name='number',
        ),
        migrations.AddField(
            model_name='request_to_repair',
            name='inventory_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Equipment', verbose_name='ИНВ №'),
        ),
    ]
