# Generated by Django 2.1.7 on 2019-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0021_auto_20190403_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_to_repair',
            name='description_failure',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание неисправности'),
        ),
        migrations.AlterField(
            model_name='request_to_repair',
            name='inventory_number',
            field=models.CharField(default='0-53554', max_length=50, verbose_name='ИНВ №'),
        ),
    ]
