# Generated by Django 2.1.7 on 2019-04-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0022_auto_20190404_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_to_repair',
            new_name='RequestToRepair',
        ),
    ]
