# Generated by Django 2.1.7 on 2019-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0023_auto_20190404_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttorepair',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='requesttorepair',
            name='description_failure',
            field=models.TextField(blank=True, max_length=100, verbose_name='Краткое описание неисправности'),
        ),
    ]
