# Generated by Django 2.1.7 on 2019-04-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0024_auto_20190404_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Move_tech',
            new_name='MoveTech',
        ),
    ]
