# Generated by Django 2.1.7 on 2019-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0025_auto_20190405_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttorepair',
            name='inventory_number',
            field=models.CharField(max_length=50, verbose_name='ИНВ №'),
        ),
    ]
