# Generated by Django 2.1.7 on 2019-04-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0026_auto_20190405_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_failure', models.TextField(blank=True, max_length=100, verbose_name='Краткое описание заявки')),
                ('complainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Employees', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявку на приобретение',
                'verbose_name_plural': 'Заявки на приобретение',
            },
        ),
        migrations.AlterModelOptions(
            name='requesttorepair',
            options={'verbose_name': 'Заявку на ремонт', 'verbose_name_plural': 'Заявки на ремонт'},
        ),
    ]
