# Generated by Django 2.1.7 on 2019-04-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0027_auto_20190406_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='description_failure',
            new_name='description_acquisition',
        ),
    ]
