# Generated by Django 2.1.7 on 2019-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0030_auto_20190409_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttorepair',
            name='location',
            field=models.CharField(default='tam', max_length=100, verbose_name='Местонахождение'),
        ),
    ]
