# Generated by Django 2.1.7 on 2019-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0033_requesttorepair_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttorepair',
            name='phone',
            field=models.CharField(default='2354', max_length=20, verbose_name='Телефон'),
        ),
    ]
