# Generated by Django 2.1.7 on 2019-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0034_auto_20190415_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='room',
            field=models.CharField(default='435', max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания заявки'),
        ),
    ]
