# Generated by Django 2.1.7 on 2019-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0036_auto_20190415_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttorepair',
            name='report',
            field=models.TextField(blank=True, max_length=500, verbose_name='Отчет по исправлению'),
        ),
    ]
