# Generated by Django 2.1.7 on 2019-11-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0038_remove_requesttorepair_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequestToRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, max_length=600, verbose_name='Отчет')),
                ('request_to_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_tech.RequestToRepair', verbose_name='Заявка на ремонт')),
            ],
            options={
                'verbose_name': 'Отчет по заявке на ремонт',
                'verbose_name_plural': 'Отчеты по заявкам на ремонт',
            },
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='room',
            field=models.CharField(max_length=50, verbose_name='Кабинет'),
        ),
    ]
