# Generated by Django 2.1.7 on 2019-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0039_auto_20191112_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='report',
            field=models.TextField(blank=True, db_column='inventory_number', max_length=600, verbose_name='Отчет'),
        ),
    ]
