# Generated by Django 2.1.7 on 2019-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0040_auto_20191112_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='report',
            field=models.TextField(blank=True, max_length=600, verbose_name='Отчет'),
        ),
    ]
