# Generated by Django 2.1.7 on 2019-11-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0044_auto_20191113_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrequesttorepair',
            name='time',
        ),
        migrations.AddField(
            model_name='reportrequesttorepair',
            name='time_field',
            field=models.TimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
