# Generated by Django 2.1.7 on 2019-12-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0045_auto_20191113_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dapartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
        ),
        migrations.RemoveField(
            model_name='movetech',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='movetech',
            name='worker',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Room', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Dapartament', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.Room', verbose_name='Кабинет'),
        ),
        migrations.DeleteModel(
            name='MoveTech',
        ),
    ]
