# Generated by Django 2.1.7 on 2019-12-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0047_auto_20191217_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pin_code',
            field=models.IntegerField(blank=True, default=1111, max_length=4),
        ),
    ]
