# Generated by Django 2.1.7 on 2019-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0048_employees_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='pin_code',
            field=models.IntegerField(blank=True, default=1111),
        ),
    ]
