# Generated by Django 2.1.7 on 2020-03-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0051_auto_20191218_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ИНВ №'),
        ),
    ]
