# Generated by Django 2.1.7 on 2020-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0052_auto_20200305_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttorepair',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
