# Generated by Django 2.1.7 on 2020-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0053_auto_20200310_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='fio_executor',
            field=models.CharField(max_length=150, verbose_name='ФИО исполнителя'),
        ),
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='post',
            field=models.CharField(max_length=100, verbose_name='Должность исполнителя'),
        ),
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='report',
            field=models.TextField(max_length=600, verbose_name='Отчет'),
        ),
    ]
