# Generated by Django 2.1.7 on 2020-04-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0055_requesttorepair_is_repaired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttorepair',
            name='is_repaired',
        ),
        migrations.AlterField(
            model_name='reportrequesttorepair',
            name='request_to_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_tech.RequestToRepair', verbose_name='Заявитель'),
        ),
    ]
