# Generated by Django 2.2.12 on 2020-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tech', '0058_auto_20200413_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequesttorepair',
            name='time_field',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время'),
        ),
    ]
